### ISSUE TITLE
Sideboard in linked decks.

### ISSUE THREAD

**Issue by skeet70** [ebuchmann/duelystcards#2]
"One thing I noticed is that if you link to a deck with a sideboard the sideboard doesn't show up."

Reported by David

**Comment by skeet70** [comment]
I haven't been able to reproduce this yet, I've emailed asking for more info.

**Comment by ebuchmann** [comment]
I never saved the sideboard in the deck hash, so that's why it doesn't load the sideboard.

**Comment by skeet70** [comment]
Users reported issues saving decks on the v1.2.0 including this fix. Rolled back to v1.1.0 on the live site. Don't have any actual console logs or anything yet, I'll try to reproduce the issue on a dev instance tomorrow when I'm at my dev box.

**Comment by skeet70** [comment]
https://github.com/ebuchmann/duelyst.cards/pull/14 fixed this on the API side, feature is working on the main site now.
