### ISSUE TITLE
Clear deck name and sideboard when a user clicks clear

### ISSUE THREAD

**Issue by skeet70** [ebuchmann/duelystcards#4]
Reproduction:
  * add some things to your sideboard and mainboard, add a deck name
  * click clear

Expected:
  * everything related to deck input is cleared

Observed:
  * sideboard and deck name remain

**Comment by ebuchmann** [comment]
Should be fixed on master branch.

**Comment by skeet70** [comment]
Mmk, I'll confirm after I deploy.

**Comment by skeet70** [comment]
Confirmed fixed in prod.
